### PR TITLE
feat: added algorithm concepts for MPP

### PR DESCRIPTION
**Pull request by jonrkarr**

### CODE REVIEW

**Comment by liebermeister** [comment]
Hi Jonathan, thanks a lot, the new entries look very good. 

There's only one thing I'd like to change: in the new entry "KISAO_0000685", the name and definition are a bit misleading and should be changed. I think "network configuration" sounds like the network structure itself is reconfigured, while what we want to say (I think) is that the variables in the network (in our case, metabolite and possibly enzyme concentrations) are chosen by the algorithm. 

Any ideas how this could be expressed/named more precisely?
(Also to be discussed with Elad) - see our discussion in the google doc.

Best,
Wolf

**Comment by jonrkarr** [comment]
I'm trying to communicate exactly what you interpreted -- methods for choosing an optimal parameter configuration of a model (according to some metric). I don't what to some "optimization method" because this has been reserved for the underlying optimization methods (i.e. interior point method). I don't want to say something like "parameter optimization method" because this would sound like model calibration such as PEtab.

Some other possibilities
- Optimization-based method (similar to "constraint-based modeling")
- Heuristic-based method

**Comment by liebermeister** [comment]
Mmh .. it looks like this is a complex question (especially, since we need not only decide about a proper name + description), but also to what level of abstraction we want to go .. maybe it's best to meet (also with Elad) and discuss this over video?

**Comment by jonrkarr** [comment]
I don't think there's an obvious answer. At the same time, the organization isn't particularly important. I don't think we need to overthink this.

**Comment by liebermeister** [comment]
Ok. Thank you!

**Comment by liebermeister** [comment]
Thank you Jonathan!!

Just a small typo in definition of  "biological state optimization method": accordion -> according

**Pull request merged**
